 /***************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	CompCtrlDefine.h
  * @author	
  * @version 	V3.2.0
  * @date	2022.02.16
  * @brief	Store composite control define
  * @details
  **************************************************************************************/ 
#ifndef COMP_CTRL_DEFINE_H
    #define COMP_CTRL_DEFINE_H
#endif	
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
