/***************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	CompCtrlDefine.h
  * @author	
  * @version 	V3.2.0
  * @date	2022.02.16
  * @brief	Store composite control define
  * @details
  **************************************************************************************/
#ifndef SC_IT_EXTERN_H
    #define SC_IT_EXTERN_H
#include "HeadFiles\SysFunVarDefine.h"
#endif
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
