/***************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	SysFunVarDefine.h
  * @author	
  * @version 	V3.2.0
  * @date	2022.02.16
  * @brief	Store var control and function control extern
  * @details
  **************************************************************************************/ 
#ifndef SYS_FUN_VAR_DEFINE
    #define SYS_FUN_VAR_DEFINE
#include "HeadFiles\CustomType.h"
#include "HeadFiles\UserExport.h"
#include "HeadFiles\FunctionType.h"
#include "HeadFiles\CompCtrlDefine.h"
#endif
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
