/**
 ******************************************************************************
 * @file    putchar.h
 * @author  SOC AE Team
 * @version V1.2.1
 * @date    2025-07-24
 * @brief   Header file of putchar module.
 ******************************************************************************
 * @attention
 *
 *1.This software is supplied by SinOne Microelectronics Co.,Ltd. and is only 
 *intended for use with SinOne products. No other uses are authorized. This 
 *software is owned by SinOne Microelectronics Co.,Ltd. and is protected under 
 *all applicable laws, including copyright laws. 
 *2.The software which is for guidance only aims at providing customers with 
 *coding information regarding their products in order for them to save time. 
 *As a result, SinOne shall not be held liable for any direct, indirect or 
 *consequential damages with respect to any claims arising from the content of 
 *such software and/or the use made by customers of the coding information 
 *contained herein in connection with their products.
 *
 *  COPYRIGHT 2025 SinOne Microelectronics
 ******************************************************************************
 */
 
/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef _putchar_H_
#define _putchar_H_

/* Includes ------------------------------------------------------------------*/
#include "sc92f.h"
#include "stdio.h"

 /*<Generated by EasyCodeCube begin*/
 //Forbid editing areas between the labels !!!

 /*<Generated by EasyCodeCube end>*/
/* Define ------------------------------------------------------------------*/
#if defined (SSIPENABLE)
	#include "sc92f_ssi.h"
	#define SSI_UARTFlag_TI       0x02
	#define Printf_SendData8      SSI_UART1_SendData8
	#define Printf_GetTxStatus    SSI_GetFlagStatus(SSI_UARTFlag_TI)
  #define Printf_ClearTxFlag    SSI_ClearFlag(SSI_UARTFlag_TI)
#elif defined(SSI0PENABLE)
  #include "sc92f_ssi.h"
	#define SSI0_UARTFlag_TI      0x02
	#define Printf_SendData8      SSI0_UART_SendData8
	#define Printf_GetTxStatus    SSI0_GetFlagStatus(SSI0_UARTFlag_TI)
  #define Printf_ClearTxFlag    SSI0_ClearFlag(SSI0_UARTFlag_TI);
#elif defined(SSI1PENABLE)
  #include "sc92f_ssi.h"
	#define SSI1_UARTFlag_TI      0x02
	#define Printf_SendData8      SSI1_UART_SendData8
	#define Printf_GetTxStatus    SSI1_GetFlagStatus(SSI1_UARTFlag_TI)
  #define Printf_ClearTxFlag    SSI1_ClearFlag(SSI1_UARTFlag_TI)
#elif defined(UART0PENABLE)
  #include "sc92f_uart0.h"
	#define Printf_SendData8      UART0_SendData8
	#define Printf_GetTxStatus    UART0_GetFlagStatus(UART0_FLAG_TI)
  #define Printf_ClearTxFlag    UART0_ClearFlag(UART0_FLAG_TI)
#elif defined(UART2PENABLE)
  #include "sc92f_uart2.h"
	#define Printf_SendData8      UART2_SendData8
	#define Printf_GetTxStatus    UART2_GetFlagStatus(UART2_FLAG_TI)
  #define Printf_ClearTxFlag    UART2_ClearFlag(UART2_FLAG_TI)
#elif defined(USCI0PENABLE)
  #include "sc92f_usci0.h"
	#define Printf_SendData8      USCI0_UART_SendData8
	#define Printf_GetTxStatus    USCI0_GetFlagStatus(USCI0_UART_FLAG_TI)
  #define Printf_ClearTxFlag    USCI0_ClearFlag(USCI0_UART_FLAG_TI)
#elif defined(USCI1PENABLE)
	#include "sc92f_usci1.h"
	#define Printf_SendData8      USCI1_UART_SendData8
	#define Printf_GetTxStatus    USCI1_GetFlagStatus(USCI1_UART_FLAG_TI)
	#define Printf_ClearTxFlag    USCI1_ClearFlag(USCI1_UART_FLAG_TI)
#elif defined(USCI2PENABLE)
	#include "sc92f_usci2.h"
	#define Printf_SendData8      USCI2_UART_SendData8
	#define Printf_GetTxStatus    USCI2_GetFlagStatus(USCI2_UART_FLAG_TI)
	#define Printf_ClearTxFlag    USCI2_ClearFlag(USCI2_UART_FLAG_TI)
#else
	#define Printf_SendData8      1
	#define Printf_GetTxStatus    1
	#define Printf_ClearTxFlag    1
#endif
char putchar(char c);

#endif

/******************* (C) COPYRIGHT 2025 SinOne Microelectronics *****END OF FILE****/