/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
/*****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	main.c
  * @author	
  * @version 	V3.2.0
  * @date	2022.02.16
  * @brief	Main Function
  * @details Contains the MCU initialization function and its H file
  ***************************************************************************************************/ 


#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "global\wm_global.h"

/**
  * @brief This function implements main function.
  * @note 
  * @param
  */
void main(void)
{
  EA = 0;	// Disable All Inerrupt
  SC_TIM1_Init();
	EA = 1;	// Enable All Interrupt after Init success
  wm_DelayMS(500); //Keep this minimum Delay
	SC_PWM_Init();	// Init PWM on start to prevent Auto Triggering Geature Block
	TouchKeyInit();  // keep this statement Before IcResourceInit, To Avoid longer startup delay
  IcResourceInit();
  
  // EA = 0;	// Disable All Inerrupt
	Uart_init();
  wm_DelayMS(1500); //Keep this minimum Delay
	WDT_Cmd(ENABLE);

  wm_OnStartUp();

	WDT_SetReload();  // Reset WDT on Start
	
	// EA = 1;	// Enable All Interrupt after Init success

    /*****MainLoop*****/
    while(1)
    {		
        /***User program***/
        if(wm_IsTkScanRoundFinished == FALSE)
        {
          wm_sys_tk_scan();       
        }
        wm_StateFlow();
      //WDT_SetReload();

    }  
}
