/***************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	CompCtrlDefine.h
  * @author	
  * @version 	V3.2.0
  * @date	2022.02.16
  * @brief	Store composite control define
  * @details
  **************************************************************************************/ 
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
void IcResourceInit()
{
    /*<UserCodeStart>*//*<SinOne-Tag><37>*/
        SC_Init(); /***MCU init***/
        
    /*<UserCodeEnd>*//*<SinOne-Tag><37>*/
}

/*************************************.Generated by EasyCodeCube.************************************/
