/*****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	SC_Init.c
  * @author	
  * @version 	V1.1009
  * @date	2024/11/27
  * @brief	Contains the MCU initialization function and its C file
  * @details 
  ***************************************************************************************************/ 

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SC_itExtern.h"

//*************************************************************
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU初始化函数
  * @note 
  * @param
  */
void SC_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*write initial function here*/	
	EA = 1;	
}

/**
  * @brief OPTION配置初始化函数
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*OPTION_Init write here*/		
}

/**
  * @brief GPIO初始化函数
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*GPIO_Init write here*/		
}

/**
  * @brief UART0初始化函数
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*UART0_Init write here*/		
}

/**
  * @brief TIMER0初始化函数
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*TIM0_Init write here*/		
}

/**
  * @brief TIMER1初始化函数
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*TIM1_Init write here*/	
}

/**
  * @brief TIMER2初始化函数
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*TIM2_Init write here*/	
}

/**
  * @brief TIMER3初始化函数
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*TIM3_Init write here*/	
}

/**
  * @brief TIMER4初始化函数
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*TIM4_Init write here*/	
}

/**
  * @brief PWM初始化函数
  * @note 
  * @param
  */
void SC_PWM_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PWM_Init write here*/	
}

/**
  * @brief PWM0初始化函数
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PWM0_Init write here*/	
}

/**
  * @brief PWM1初始化函数
  * @note 
  * @param
  */
void SC_PWM1_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PWM1_Init write here*/	
}

/**
  * @brief PWM2初始化函数
  * @note 
  * @param
  */
void SC_PWM2_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PWM2_Init write here*/	
}

/**
  * @brief PWM3初始化函数
  * @note 
  * @param
  */
void SC_PWM3_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PWM3_Init write here*/	
}

/**
  * @brief PWM4初始化函数
  * @note 
  * @param
  */
void SC_PWM4_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PWM4_Init write here*/	
}

/**
  * @brief INT初始化函数
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*INT_Init write here*/	
}

/**
  * @brief ADC初始化函数
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*ADC_Init write here*/
}

/**
  * @brief PGA初始化函数
  * @note 
  * @param
  */
void SC_PGA_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PGA_Init write here*/
}

/**
  * @brief IAP初始化函数
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*IAP_Init write here*/		
}

/**
  * @brief USCI0初始化函数
  * @note 
  * @param
  */
void SC_USCI0_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*USCI0_Init write here*/		
}

/**
  * @brief USCI1初始化函数
  * @note 
  * @param
  */
void SC_USCI1_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*USCI1_Init write here*/		
}

/**
  * @brief USCI2初始化函数
  * @note 
  * @param
  */
void SC_USCI2_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*USCI2_Init write here*/		
}

/**
  * @brief USCI3初始化函数
  * @note 
  * @param
  */
void SC_USCI3_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*USCI3_Init write here*/		
}

/**
  * @brief USCI4初始化函数
  * @note 
  * @param
  */
void SC_USCI4_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*USCI4_Init write here*/		
}

/**
  * @brief USCI5初始化函数
  * @note 
  * @param
  */
void SC_USCI5_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*USCI5_Init write here*/		
}

/**
  * @brief SSI初始化函数
  * @note 
  * @param
  */
void SC_SSI_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*SSI_Init write here*/		
}

/**
  * @brief SSI0初始化函数
  * @note 
  * @param
  */
void SC_SSI0_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*SSI0_Init write here*/		
}

/**
  * @brief SSI1初始化函数
  * @note 
  * @param
  */
void SC_SSI1_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*SSI1_Init write here*/		
}

/**
  * @brief 低频时钟定时器初始化函数
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*BTM_Init write here*/		
}

/**
  * @brief CRC 初始化函数
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*CRC_Init write here*/	
}

/**
  * @brief check sum 初始化函数
  * @note 
  * @param
  */
void SC_CHKSUM_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*CHKSUM_Init write here*/	
}

/**
  * @brief 看门狗初始化函数
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*WDT_Init write here*/		
}

/**
  * @brief 电源/功耗控制初始化函数
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*PWR_Init write here*/		
}

/**
  * @brief 显示控制初始化函数
  * @note 
  * @param
  */
void SC_DDIC_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*DDIC_Init write here*/	
}

/**
  * @brief 运放初始化函数
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*ACMP_Init write here*/	
}

/**
  * @brief 乘除法器初始化函数
  * @note 
  * @param
  */
void SC_MDU_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*MDU_Init write here*/	
}

/**
  * @brief LPD初始化函数
  * @note 
  * @param
  */
void SC_LPD_Init(void)
{
	//Forbid editing areas before the following label !!!
	/*LPD_Init write here*/
}
