/*****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	SysFunVarDefine.c
  * @author	
  * @version 	V2.0
  * @date	2021.04.08
  * @brief	Store var control and function control define
  * @details 
  ***************************************************************************************************/ 
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
//**********************************************************************
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
